/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import javax.swing.JButton;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Wilson Steven Rodriguez
 * @author Jhony Rojas
 * Capa visual
 */
public class Vista extends javax.swing.JFrame {

    /**
     * Objetos de la parte grafica
     */
    public JButton ingresar;
    private JPanel a,b;
    public JList lista;
    public JTextField campoTexto;
    
    /**
     * COnstructor donde se agregan los paneles y botones a la parte visual
     */
    
    public Vista() {
       
       getContentPane().setLayout(new BorderLayout());
       this.setMinimumSize(new Dimension(600, 600)); 
       
        a = new JPanel();
        b = new JPanel();
        a.setLayout(new FlowLayout());
        b.setLayout(new FlowLayout());
        lista = new JList();
        ingresar = new JButton("Ingresar Palabra");
        campoTexto = new JTextField(20);
        lista.setSelectionMode(ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        lista.setLayoutOrientation(JList.HORIZONTAL_WRAP);
        a.add(campoTexto);
        a.add(ingresar);
        b.add(lista);
        a.setBackground(Color.BLACK);
        b.setBackground(Color.lightGray);
        
        
        
        add(a, BorderLayout.NORTH);
        
        add(b, BorderLayout.CENTER);
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
